# Subfolders

dir.create("R")
dir.create("R/Functions")
dir.create("Data")
dir.create("Output")
dir.create("Output/Data")
dir.create("Output/Data/Model/Summary")
dir.create("Output/Data/Model2")
dir.create("Output/Data/Model2/Summary2")
dir.create("Output/Data/Model/Prediction")
dir.create("Output/Data/Model/Prediction2")
dir.create("Output/Plots")
dir.create("Output/Plots/RawData")
dir.create("Output/Plots/Model")
dir.create("Output/Plots/Model2")
dir.create("Output/Plots/Regressions")
dir.create("Output/Plots/Regressions/Model")
dir.create("Output/Plots/Regressions/Model2")
