# Subfolders

dir.create("R")
dir.create("R/Air")
dir.create("R/Water")
dir.create("R/Sediment")
dir.create("Data")
dir.create("Output")
dir.create("Output/Data")
dir.create("Output/Data/Air")
dir.create("Output/Data/Air/Model")
dir.create("Output/Data/Air/Model/Summary")
dir.create("Output/Data/Air/Model/Prediction")
dir.create("Output/Data/Air/Model/Prediction2")
dir.create("Output/Data/Air/Model2")
dir.create("Output/Data/Air/Model2/Summary2")
dir.create("Output/Plots")
dir.create("Output/Plots/Air")
dir.create("Output/Plots/Air/RawData")
dir.create("Output/Plots/Air/Model")
dir.create("Output/Plots/Air/Model2")
dir.create("Output/Plots/Air/Regressions")
dir.create("Output/Plots/Air/Regressions/Model")
dir.create("Output/Plots/Air/Regressions/Model2")
